services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\SockBundle\Provider\DataTypeProvider:
        public: true
        tags:
            - { name: data_type_provider }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\BuildProvisioner:
        tags:
            - { name: domainator.provisioner.build, priority: 50 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\DestroyProvisioner:
        tags:
            - { name: domainator.provisioner.destroy, priority: 50 }
    DigipolisGent\Domainator9k\SockBundle\FieldType\ParentApplicationFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SockServerFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\ManageSockFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SshKeyChoiceFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SockApplicationTechnologyFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\DatabaseHostFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\Service\ApiService:
